shiboken6_generator: Handle forward declarations containing struct with Clang 22
Strip "struct " from type names.
Amends 27cb9caa4980620cdd055cc82e080056dd22c13c.

This fixes the rejection of:

"Display* QNativeInterface::QX11Application::display()const: unmatched return type 'Display*':
  Unable to translate type "Display*": Cannot find type entry for "struct _XDisplay".

(via gui/platform/unix/qtx11extras_p.h:24:typedef struct _XDisplay Display).

Task-number: PYSIDE-3286
Change-Id: Ie6617b62e4f9dde101e31179ad9d4db9478004cd
Reviewed-by: Shyamnath Premnadh <Shyamnath.Premnadh@qt.io>
(cherry picked from commit ddd6b00de284657c2fb62b4e80001d2a9ce7a53f)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>