PySide6: Fix the test HTTP server
Change the test data to be a bytearray, fixing:

File "sources/pyside6/tests/util/httpd.py", line 47, in do_GET
    self.wfile.write(TestHandler.DATA)
  File "/usr/lib/python3.8/socketserver.py", line 799, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'

Change-Id: I5a0b5d0f76c4245fc7209d17a6c7f1e664cbc04f
Reviewed-by: Christian Tismer <tismer@stackless.com>
(cherry picked from commit bdcc883a5a088a8ede3f01d83cf565713a8ad5f7)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>