shiboken6/tests: Fix compilation with MSVC 2022 in C++ 20 mode
Make operator==() of test class Size an inline friend like operator!=().

It seems that in C++ 20 mode, the compiler tries to include operator==() in
overload checks of operator!=() (rewriting expressions) and hits on an
amiguity when operator==() is implemented as member (arguable a compiler
bug):

size_wrapper.cpp(921): error C2666: "Size::operator ==": 3 overloads have similar conversions

Change-Id: Ia57d531adca272be29dd4c4f7ef322450986033e
Reviewed-by: Shyamnath Premnadh <Shyamnath.Premnadh@qt.io>
Reviewed-by: Christian Tismer <tismer@stackless.com>
(cherry picked from commit 27bcf6ad7afb7b5415c6c8dc79331f73e068923b)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>