QtSensors test: Handle failed readings
Failures have been observed on Windows:
qt.sensors.winrt: Unable to initialize orientation sensor factory. "CoInitialize has not been called."
    for i in range(0, reading.valueCount()):
    AttributeError: 'NoneType' object has no attribute

Traceback (most recent call last):

Change-Id: I67d2645b722666631c640bea865f2966b3deb130
Reviewed-by: Christian Tismer <tismer@stackless.com>