PySide6/signature: Fix error handling
Raise an error if != 2 tokens are obtained from the argument,
changing

packages/shiboken6/files.dir/shibokensupport/signature/parser.py", line 121, in _parse_line
    name, ann = tokens
ValueError: too many values to unpack (expected 2)

to

packages/shiboken6/files.dir/shibokensupport/signature/parser.py", line 119, in _parse_line
    raise SystemError(f'Invalid argument "{arg}" in "{line}".')
SystemError: Invalid argument "method:QWebEngineHttpRequest::Method" in "0:PySide6.QtWebEngineCore.QWebEngineHttpRequest(self,url:typing.Union[PySide6.QtCore.QUrl, QString]=QUrl(),method:QWebEngineHttpRequest::Method)".

Change-Id: I16e0f32bb3332deadc0a8819a6ba7abd6b12a941
Reviewed-by: Cristian Maureira-Fredes <cristian.maureira-fredes@qt.io>
(cherry picked from commit e6fb38a92efac1e098a87d2a6947807708652369)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>