Fix build with MSVC
Add  /Zc:__cplusplus, fixing:
QtCore/qcompilerdetection.h(1257): fatal error C1189: #error:
"Qt requires a C++17 compiler, and a suitable value for __cplusplus.
On MSVC, you must pass the /Zc:__cplusplus option to the compiler."

Also update the emulated MSVC version for libclang 18.

Pick-to: 6.7 6.6 6.5 6.2
Change-Id: Iacbdf1da3bc1f73757ff5231391ebe847158cc2d
Reviewed-by: Adrian Herrmann <adrian.herrmann@qt.io>