Fix build error on Windows caused by macro copysign in CPython
Remove the define, fixing:
qjsprimitivevalue.h(805): error C2039: '_copysign': is not a member of 'std'

Change-Id: Iad9b467decc81a3eed534f49d26e30237eef23de
Reviewed-by: Shyamnath Premnadh <Shyamnath.Premnadh@qt.io>
Reviewed-by: Christian Tismer <tismer@stackless.com>
(cherry picked from commit 9aa0225352cada0c7957f4310b9be9d3d0922f56)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>