Fix build with MSVC
Add  /Zc:__cplusplus, fixing:
QtCore/qcompilerdetection.h(1257): fatal error C1189: #error:
"Qt requires a C++17 compiler, and a suitable value for __cplusplus.
On MSVC, you must pass the /Zc:__cplusplus option to the compiler."

Also update the emulated MSVC version for libclang 18.

Pick-to: 6.5 6.2
Change-Id: Iacbdf1da3bc1f73757ff5231391ebe847158cc2d
Reviewed-by: Adrian Herrmann <adrian.herrmann@qt.io>
(cherry picked from commit fce8fc22efe52b0d8b6f1f4633e8cc64e6641d2c)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit 114d900b011123cbc9cbd79b720105201bae8aa5)