Fix crash when running a limited API build of 3.9 in 3.12
The size of propertyobject as needed as basic size of PyClassProperty_spec needs to be adapted according to runtime version.

Otherwise, PyType_FromSpecWithBases  fails with:
TypeError: tp_basicsize for type 'PySide6.QtCore.PyClassProperty' (56) is too small for base 'property' (64)

Pick-to: 6.6 6.5
Task-number: PYSIDE-2230
Change-Id: I03788edbb7031577f37db0fb2eb029b41f37c5f1
Reviewed-by: Shyamnath Premnadh <Shyamnath.Premnadh@qt.io>