stubs: add type for os.PathLike type hints
Specifying 'str' for os.PathLike solves
the issues found with tools like pyright.

For example, for QUrl.fromLocalFile:

error: Type of "fromLocalFile" is partially unknown
  Type of "fromLocalFile" is "(localfile: str | bytes | PathLike[Unknown]) -> QUrl" (reportUnknownMemberType)

Using the string of the annotation to avoid an issue
when Python tries to evaluate it at Runtime (see mypy issue #5667)

Fixes: PYSIDE-2280
Change-Id: Ib63bfe8636fbf6cbf1e393d29ef3caf9af0fb4c7
Reviewed-by: Shyamnath Premnadh <Shyamnath.Premnadh@qt.io>
(cherry picked from commit 0e62a3d9903dd22391b769e0df0d37fdb9110d88)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>