Fix non-unity build
Add sbkpep.h, fixing:
sources/shiboken6/libshiboken/sbkbindingutils.cpp:90:35: error: use of undeclared identifier 'PepEval_GetFrameBuiltins'; did you mean 'PyEval_GetBuiltins'?

Amends ec680ac8090d903b07241dbad17d123621ffaa32.

Task-number: PYSIDE-3351
Change-Id: I6cd4f7f009068bf505a7877197bc90d5b9124825
Reviewed-by: Cristian Maureira-Fredes <cristian.maureira-fredes@qt.io>
(cherry picked from commit e2c54140d7777515aa181cbd4b71e4aa1bf7c91d)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>