signature: Add support for classmethods
Two tests were adapted, because now the missing signature
error message:

    TypeError: xxx.__dict__['yyy'].fset(<class 'object'>) is wrong (missing signature)

does not apply, and we get the usual message:

    TypeError: xxx.__dict__['yyy'].fset" called with wrong argument types:

this comes from the fact that we are not getting the string
representation of the signature, but the data type itself.

Change-Id: Ib9c8b7f863063b384c41dea32e2b4b01f0695f82
Fixes: PYSIDE-1955
Pick-to: 6.6 6.5 6.2
Reviewed-by: Qt CI Bot <qt_ci_bot@qt-project.org>
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@qt.io>