Fix non-unity build compilation error: anystringview_helpers.h
Fixes non-unity build compilation error in anystringview_helpers.h
(missing qsizetype). Amends 16098891ad21c2ba984582a1de770e49f961f22b.

Pick-to: 6.7
Task-number: PYSIDE-2792
Fixes: PYSIDE-2804
Change-Id: Ia6d08ce162c66464da5325f53fa564c7a3c6cce6
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@qt.io>