Deployment: Relative path bug fix
- The qml files are identified and stored as relative path and line
  under consideration tries to do a 'relative_to()' on an absolute path
  which causes the error

  ValueError: {qml_file} is not in the subpath of 'project_path' OR
  one path is relative and the other is absolute.

  The error only appears on the first run of pyside6-deploy with a
  project that does not have a .pyproject file. For the subsequent
  runs, absolute path are used because the path is fetched from the
  deploy config file.
- This patch fixes this error by using absolute path for each qml_file

Pick-to: 6.5
Task-number: PYSIDE-1612
Change-Id: Ib54edded404bd1be87ab5f22f61e2d30416b7dae
Reviewed-by: Cristian Maureira-Fredes <cristian.maureira-fredes@qt.io>
(cherry picked from commit b0de21cea7f01db97a46d72d8edcb7944aaa4387)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>