shiboken6: Fix compile error in tests
sources/shiboken6/tests/libsample/functions.cpp:244:33: error: use of overloaded operator '<<' is ambiguous
(with operand types 'basic_ostream<char, std::__1::char_traits<char> >' and 'std::nullptr_t' (aka 'nullptr_t'))
 cout << __FUNCTION__ << ' ' << t << '\n';

Amends 8ecb8a909ecde13f179b8fce170582e47373f50c.

Task-number: PYSIDE-854
Change-Id: Ifd2bb6ac4bf27ebcb240359020a6f8e18dbfef79
Reviewed-by: Christian Tismer <tismer@stackless.com>
(cherry picked from commit e5e4d388ab9a8a94c341e644ad00dd8a98980063)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>