PySide6: Work around uic feature test failure
Use QCoreApplication.process_events() instead of
qApp..process_events() which causes:
AttributeError: 'PySide6.QtWidgets.QApplication' object has no attribute 'process_events'

Amends 9b5fa60d1fed5025e97c393ba1bab80f81ba833a.

Task-number: PYSIDE-1626
Pick-to: 6.1
Pick-to: 5.15
Change-Id: I7a268c8fa5b699813dfcb37a3093bd897fec381c
Reviewed-by: Christian Tismer <tismer@stackless.com>