PySide6/QtGui: Fix crashes in functions returning internally owned classes by pointer
Indicate Default ownership, for QClipboard.mimeData(),
QTextCursor.currentList(), QTextCursor.currentTable(), fixing:

RuntimeError: Internal C++ object (PySide6.QtCore.QMimeData) already deleted.
RuntimeError: Internal C++ object (PySide6.QtGui.QTextList) already deleted.

[ChangeLog][PySide6] Crashes in QClipboard.mimeData(),
QTextCursor.currentList() and QTextCursor.currentTable()
have been fixed.

Change-Id: I1e4f55856bce8bf951edd8579331f0242e904ae6
Reviewed-by: Christian Tismer <tismer@stackless.com>
(cherry picked from commit 8cd50636102be2e1178c8c602a3e374891398e3e)