PySide2: Fix flaky test feature_with_uic_test.py
Add missing import, fixing:
Traceback (most recent call last):
File "C:/Users/qt/work/pyside/tqtc-pyside-setup/sources/pyside2/tests/QtCore/feature_with_uic_test.py", line 72, in testFeaturesWorkWithUIC
     QCoreApplication.process_events()
 NameError: name 'QCoreApplication' is not defined

Amends d57e16a89fb963c7416f6a9875773ac0edbcb032.
Task-number: PYSIDE-1626

Change-Id: I25508996c0aa4a12afb6be25bf92e35442c04864
Reviewed-by: Christian Tismer <tismer@stackless.com>