shiboken6: Clean up messages about cyclic dependencies of overloaded functions
Move message helper msgCyclicDependency() from overloaddata.cpp
to message.cpp to prevent a clash between the static helper
and the one declared in messages.h.
This was an oversight causing problems in 5.15:

tqtc-pyside-setup/sources/shiboken2/generator/shiboken2/overloaddata.cpp: In function ‘QString msgCyclicDependency(const QString&, const QString&, const MetaFunctionList&)’:
tqtc-pyside-setup/sources/shiboken2/generator/shiboken2/overloaddata.cpp:151:16: error: ‘QString msgCyclicDependency(const QString&, const QString&, const MetaFunctionList&)’
   was declared ‘extern’ and later ‘static’ [-fpermissive]

Pick-to: 6.2 5.15
Change-Id: I56375c5bbc483859f83658cfeb4df1e6067421a0
Reviewed-by: Christian Tismer <tismer@stackless.com>