Add shibokenmodule dependency for all _pyi modules
When building on Fedora rawhide, we sometimes end up running
generate_pyi.py script while shibokenmodule is still being built,
resulting in the following error message:

ImportError: (...)/Shiboken.cpython-313-x86_64-linux-gnu.so: file too
short

Change-Id: I500679bf12e4ba5a820db6c7971f8cdb0012b965
Reviewed-by: Christian Tismer <tismer@stackless.com>
Reviewed-by: Łukasz Patron <priv.luk@gmail.com>
(cherry picked from commit 2b77370de90e9a342b3d00f6bb5c44e70579b458)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>