Fix some bitrot in examples
examples/widgets/graphicsview/elasticnodes/elasticnodes.py", line 132, in __init__
    self.setCacheMode(self.DeviceCoordinateCache)
AttributeError: 'Node' object has no attribute 'DeviceCoordinateCache'

examples/charts/chartthemes/main.py:137: DeprecationWarning: Function: 'QXYSeries.pointsVector() const' is marked as deprecated
  points = lower_series.pointsVector()
examples/charts/chartthemes/main.py:148: DeprecationWarning: Function: 'QChart.axisX(QAbstractSeries * series) const' is marked as deprecated
  chart.axisX().setRange(0, self.value_count - 1)

examples/charts/percentbarchart/percentbarchart.py:46: DeprecationWarning: Function: 'QChart.setAxisX(QAbstractAxis * axis, QAbstractSeries * series)' is marked as deprecated
   chart.setAxisX(axis, series)

Task-number: PYSIDE-841
Change-Id: Ifc7a539f547b5986055a56b98d59ca00c5b51e19
Reviewed-by: Christian Tismer <tismer@stackless.com>
(cherry picked from commit 81c0c6d8ca57485cdaec68474fc879416f8fbecb)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>