PySide6: Fix QThreadPool test
The test used deprecated/removed functions of QTime,
causing:
AttributeError: 'PySide6.QtCore.QTime' object has no attribute 'start'

Use QThread instead.

Change-Id: Ib6c7d043d3386eae3c1145b5966c86bc8c31562f
Reviewed-by: Cristian Maureira-Fredes <cristian.maureira-fredes@qt.io>
(cherry picked from commit d3877ec7445bc7719aff233bae16243b563d5a04)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>