Fix build error on Windows caused by macro copysign in CPython
Remove the define, fixing:
qjsprimitivevalue.h(805): error C2039: '_copysign': is not a member of 'std'

Pick-to: 6.3 6.2
Change-Id: Iad9b467decc81a3eed534f49d26e30237eef23de
Reviewed-by: Shyamnath Premnadh <Shyamnath.Premnadh@qt.io>
Reviewed-by: Christian Tismer <tismer@stackless.com>