snippet translate: Fix error
Adapt to get_snippets() returning a list after
168f0c941cefe2fcdaaa12498272f181fe246986:

File "pyside-setup-devt/tools/snippets_translate/converter.py", line 21, in snippet_translate
    if x.strip().startswith("content-type: text/html"):
AttributeError: 'list' object has no attribute 'strip'

Change-Id: I3366b6fcf7647e24cf50ad7afe1f62ff0d04f9e2
Reviewed-by: Christian Tismer <tismer@stackless.com>
(cherry picked from commit b5ca9db036e9380c05b2291cefe9b0b4f735fcce)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>