Fix dependencies of QtQuick3D
Fix error:
QtQuick3D/pyside6_qtquick3d_python.h:50:10: fatal error: pyside6_qtquick_python.h: No such file or directory
   50 | #include <pyside6_qtquick_python.h>

Amends b9ec49942b3ad53343317e631320c58e59736c22.

Fixes: PYSIDE-1708
Change-Id: I0de9400c9db582a21d8e3e9f859e1e2246fb8328
Reviewed-by: Alexandru Croitor <alexandru.croitor@qt.io>
(cherry picked from commit c94bc617282e0834ee71692e876d96d9d7ee7012)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>