PySide6: Fix qcalendar_test.py on Windows/debug
There is apparently some clash between QCalendar(QCalendar::System)/
QCalendar(size_t) on Windows, causing:

======================================================================
ERROR: testCalendar (__main__.TestQCalendar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "sources/pyside6/tests/QtCore/qcalendar_test.py", line 47, in testCalendar
    calendar = QCalendar(QCalendar.System.Gregorian)
TypeError: Invalid type for unsigned long long conversion

Reorder the overloads manually to prevent this.

Note this is only in debug mode.

Pick-to: 6.1
Change-Id: I1de706d9bf8456a27ae68f995c6d744ce29ae23c
Reviewed-by: Christian Tismer <tismer@stackless.com>