PySide6: Fix build against Qt 6.2.1
Fixes:
6.2.1/gcc_64/include/QtQml/6.2.1/QtQml/private/qtqmlcompilerglobal_p.h:54:10: fatal error: QtCore/private/qglobal_p.h: No such file or directory

Amends 346a4a86fc2d7064e44c0766dd08374d652cdcc1.

Add an include path for the QtCore private headers.

Task-number: PYSIDE-1709
Change-Id: I3189d4d9fe05e038634af1d0ef7bc66c16be7aab
Reviewed-by: Cristian Maureira-Fredes <cristian.maureira-fredes@qt.io>
(cherry picked from commit 15763626e56fb7d495f56e77e4c8f730f560e2f5)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>