Fix the widget gallery example
Fix error
AttributeError 'builtin_function_or_method' object has no attribute 'width'

Amends c5db9d63277201ee58829f7eb0656c534d04c249.

Task-number: PYSIDE-1112
Change-Id: I5050283a62fea5c389852168284715412cb50260
Reviewed-by: Christian Tismer <tismer@stackless.com>
(cherry picked from commit 28f61fb65c1f2fef5757c1bc6f92dcd62d86d34e)
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@qt.io>