PySide6: Fix QThreadPool test
The test used deprecated/removed functions of QTime,
causing:
AttributeError: 'PySide6.QtCore.QTime' object has no attribute 'start'

Use QThread instead.

Pick-to: 6.1
Change-Id: Ib6c7d043d3386eae3c1145b5966c86bc8c31562f
Reviewed-by: Cristian Maureira-Fredes <cristian.maureira-fredes@qt.io>