Use PlatformCommonInternal to fix musl build
Compilation with musl c library fails with

In file included from sources/pyside6/libpyside/pyside.cpp:62:
/usr/include/QtCore/6.10.2/QtCore/private/qcore_unix_p.h: In function 'int qt_safe_open(const char*, int, mode_t)':
/usr/lib/mkspecs/linux-g++/../common/posix/qplatformdefs.h:26:35: error: '::open64' has not been declared; did you mean 'openat'?
   26 | #define QT_OPEN                 ::open64
      |                                   ^~~~~~

Needed compiler flags are available from PlatformCommonInternal.

Pick-to: 6.10 6.8
Change-Id: Id128cad944ded99944f457e730484310218b8c62
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@qt.io>
(cherry picked from commit 24979b3124663acc0ef48350a1ecdc9a4b96d75a)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>