Fix test property_python_test.py to pass in debug mode
Pass None for the functions, fixing:

Traceback (most recent call last):
  File ".../test/support/__init__.py", line 1307, in trace_wrapper
    return func(*args, **kwargs)
  File "sources/pyside6/tests/pysidetest/property_python_test.py", line 207, in test_refleaks_in___init__
    fake_prop = Property(object, 'fget', 'fset', "freset", 'fdel', 'doc')
TypeError: Non-callable parameter given for "fget".

Pick-to: 6.8
Change-Id: I9b71ad097fbb37a1a6702f456e9e151e89006c01
Reviewed-by: Cristian Maureira-Fredes <cristian.maureira-fredes@qt.io>
Reviewed-by: Shyamnath Premnadh <Shyamnath.Premnadh@qt.io>
(cherry picked from commit c11820f10796739c927f8a1210cffc8b3d50056a)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>