shiboken6: Fix build with Qt 6.9
Fix a bug uncovered by qtbase/365904085e27b49d402e389d5c454781eca4f3f5,
making QFile constructors explicit:
qtdoc/qtdocgenerator.cpp:1052:59: error: invalid initialization of reference of type 'const QFile&' from expression of type 'QString'

Task-number: PYSIDE-2862
Change-Id: I864f9d0aa49219161e9ea8cee66f3d36528d7a44
Reviewed-by: Christian Tismer <tismer@stackless.com>
(cherry picked from commit 8c4a749c4b1802160fa27033f8f7333fc05db932)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>