shiboken: add missing include
Amend b829abcc7b2e9fcdb027e653a6a52cdb0706de11 and add missing include
to fix:

 | sbkmodule.cpp:459:15: error: ‘Shiboken::Conversions’ has not been declared
 |     Shiboken::Conversions::clearNegativeLazyCache();
 |               ^~~~~~~~~~~

Pick-to: 6.7
Fixes: PYSIDE-2765
Task-number: PYSIDE-2749
Task-number: PYSIDE-2404
Change-Id: I13625848bff3b0e90a53649104d6e5d84553a984
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@qt.io>