build_scripts: Fix install target
Fix: File "pyside-setup/build_scripts/main.py", line 271, in install
    if self.build_dir.is_dir():
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'is_dir'

Amends 00093e017e5b987cffa5b8a0d57fff97faa47945.

Change-Id: I4a1d9c277632e1304f2af94c2ef6f942a7aa54ec
Reviewed-by: Cristian Maureira-Fredes <cristian.maureira-fredes@qt.io>
(cherry picked from commit 49ca70133d96758a6344203138cf876697064bce)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>