Build system: Exclude broken version of setuptools
Apparently, version 60.X (up including 62) introduces a bug
manifesting in imports not found:

ImportError: cannot import name 'build_py' from 'setuptools._distutils.command'

https://github.com/pypa/setuptools/issues/2353

Change-Id: I4c08d61ed95998221fa560915011f5ad2ef8f58b
Reviewed-by: Christian Tismer <tismer@stackless.com>